/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
  
var map = {};
map["Taipei City"] = "2306179";
map["New Taipei City "] = "2306211";
map["Keelung"] = "2306188";
map["Taoyuan"] = "2306184";
map["Hsinchu City"] = "2306185";
map["Hsinchu County"] = "2306185";
map["Miaoli"] = "2306229";
map["Nantou"] = "2306204";
map["Taichung"] = "2306181";
map["Changhua"] = "2306201";
map["Yunlin"] = "2306250";
map["Kinmen"] = "2306250";
map["Kaohsiung"] = "2306199";
map["Yilan"] = "2306198";
map["Penghu"] = "2306198";
map[" Pingtung"] = "2306213";
map["Chiayi City"] = "2306206";
map["Chiayi County"] = "2306206";
map["Pingtung "] = "2306224";
map["Tainan"] = "2306193";
map["Hualien"] = "2306187";
map["Taidong"] = "2306227";
map["Lianjiang"] = "2306227";

/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    var myDate = new Date();      
    $('#big').text((myDate.getMonth()+1)+ "/" + myDate.getDate());
    
    var table = document.getElementById('foreC')
	  var weather, feed, title, content,  
    rss = 'http://weather.yahooapis.com/forecastrss?w=' + map[$(this).text()] + '&u=c',
    url = 'https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&callback=?&q=' + encodeURIComponent(rss);  
    $.ajax({  
        type: "GET",  
        url: url,  
        dataType: "json",  
        error: function (e) {  
          console.log('oh no');  
        },  
    
        success: function (e) {  



          weather = $(e);  
          var feed = weather[0].responseData.feed;  
          content = feed.entries[0].content;  

          var ss = content.split("<br>");
          var current = ss[2];
          
          $('#now').text(current);
          $('#cityName').text(feed.description);

          var entry = e.responseData.feed.entries[0];
          var content = entry.content;
          var content_piece = content.split("<br>");
          
          var skycons = new Skycons();
              skycons.add()
                  if(current.indexOf("Rain") > -1){
                    skycons.set("today", Skycons.RAIN);
                  }else if(current.indexOf("Sun") > -1){
                    skycons.set("today", Skycons.CLEAR_DAY);
                  }else if(current.indexOf("Cloud") > -1) {
                    skycons.set("today", Skycons.CLOUDY);
                  }else if(current.indexOf("Wind") > -1) {
                    skycons.set("today", Skycons.WIND);
                  }
                  skycons.play();

          for(var i=6; i<10; i++){

            
            var pair = content_piece[i].split(".");
            var day = pair[0].split("-")[0].trim();
            
            var c = table.childNodes[1].childNodes[2*(i-6)]; // 0: 0, 2: 1, 4: 2
            c.childNodes[1].innerHTML = (myDate.getMonth() + 1)+ "/"+ (myDate.getDate()+1) + " " + day;
            myDate.setDate(myDate.getDate() + 1);
            var weather = pair[0].split("-")[1].trim();
            c.childNodes[3].innerHTML = weather;
            var h_index = pair[1].indexOf("High");
            var l_index = pair[1].indexOf("Low");
            var high = pair[1].substring(h_index, l_index).trim();
            c.childNodes[5].innerHTML = high;
            var low = pair[1].substring(l_index).trim();
            c.childNodes[7].innerHTML = low;
          }
            
        } 
            

      });  
});








